project:
  type: website

website:
  title: "Repeated Features within and across SAE's"
  navbar:
    left:
      - href: post.qmd
        text: "Sparse Autoencoders"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    css: custom.css
    highlight-style: github
