project:
  type: website

website:
  title: "...?"
  navbar:
    left:
      - href: post.qmd
        text: "Mechninterp/Explainability"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    css: custom.css
    highlight-style: github
